spring.application.name=gateway-service
server.port=8080

downstream.iam.base-url=http://localhost:8081
downstream.auction.base-url=http://localhost:8082
downstream.catalogue.base-url=http://localhost:8083
downstream.payment.base-url=http://localhost:8084
downstream.leaderboard.base-url=http://localhost:8085
